let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "MSI PRO Z690",
    price: 145,
    desc: "Motherboard.",
    img: "images/img-1.1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: " GIGABYTE B460m ",
    price: 180,
    desc: "Motherboard.",
    img: "images/img-3.1.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Asus ROG Strix",
    price: 255,
    desc: "Motherboard.",
    img: "images/img-2.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "AMD Ryzen 5",
    price: 300,
    desc: "Desktop Processor.",
    img: "images/img-4.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "AMD Ryzen 7",
    price: 255,
    desc: "Desktop Processor.",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Intel Core i9",
    price: 200,
    desc: "Desktop Processor.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Rtx 3090 aorus",
    price: 450,
    desc: "Graphics card.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "GeForce RTX 3080",
    price: 445,
    desc: "Graphics card.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "GeForce RTX 3090",
    price: 845,
    desc: "Graphics card.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Armaggeddon",
    price: 120,
    desc: "PC Case.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "ZALMAN",
    price: 355,
    desc: "PC Case.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Rgb Alseye H120d",
    price: 350,
    desc: "PC Cooler.",
    img: "images/img-12.png",
  },
];
